Part1 - Nouns and Verbs
transistasis/PFMCPP_Project1 pull request #1
Opened 2021-07-12 02:53 UTC by transistasis

In this pull request:
* Added nouns and verbs to main.cpp

2021-07-12 05:23 UTC, matkatmusic requested changes

2021-07-12 05:23 UTC, matkatmusic commented on main.cpp
> +statistics.variance();
the action you used here is `computes`, but none of your pseudo-code includes this word. 
- [ ] revise

2021-07-12 05:23 UTC, matkatmusic commented on main.cpp
> +cat.stealFood();
As explained in the instructions, here is the obligatory request for some changes to get you familiar with the Pull Request Review process.
**REPLACE** the highlighted noun/action as follows:
- [ ] come up with a new noun and 3 actions
- [ ] pick a noun that needs `camelCase` for the name
- [ ] pick actions that need `camelCase` for their name.
**Do not** create an 11th noun.

2021-07-13 02:56 UTC, transistasis commented on main.cpp
> +statistics.variance();
The verb `compute` has been added to each verb. 

Also, I didn't know that you could add tick boxes to comments. Very cool!

2021-07-13 03:02 UTC, transistasis commented on main.cpp
> +cat.stealFood();
The noun `cat` has been replaced with the noun `sport bike`. All new items use `camelCase`.

2021-07-13 04:54 UTC, matkatmusic approved these changes

2021-07-13 04:54 UTC, merged